{% set version = "3.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nparcomp
  version: {{ version|replace("-", "_") }}

source:
  fn: nparcomp_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/nparcomp_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/nparcomp/nparcomp_{{ version }}.tar.gz
  sha256: f8654bb829b9d52591ec19349b1889e80453e6cce65ebed392aa75ea558b41b3

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-multcomp
    - r-mvtnorm

  run:
    - r-base
    - r-multcomp
    - r-mvtnorm

test:
  commands:
    - $R -e "library('nparcomp')"  # [not win]
    - "\"%R%\" -e \"library('nparcomp')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=nparcomp
  license: GPL2 and GPL3
  summary: With this package, it is possible to compute nonparametric simultaneous confidence
    intervals for relative contrast effects in the unbalanced one way layout. Moreover,
    it computes simultaneous p-values. The simultaneous confidence intervals can be
    computed using multivariate normal distribution, multivariate t-distribution with
    a Satterthwaite Approximation of the degree of freedom or using multivariate range
    preserving transformations with Logit or Probit as transformation function. 2 sample
    comparisons can be performed with the same methods described above. There is no
    assumption on the underlying distribution function, only that the data have to be
    at least ordinal numbers.
  license_family: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
