travis:
  secure:
    BINSTAR_TOKEN: KhASeBZ/+hbNoE+op/dR8+GNiTzJh5LRoe61AkEwDoJpXN1KAvMdUCr37Qahv5kgzjpeyPxLVNdL1ZtpnVp0X2Y152xIkTw5a3R/HotCSGoNdPGRyW7oMloXqd2I92Rue2EIUPkusOvZvzFTZQvsHjfEF+l6yLZ2c71VeISf7eQ5fICw3r7NTtYN0apsIZWcmhXjkGSJnjRVovmSWFHCMT6Kyrbwgs1ObE5YW7vtRjXm3qv0bkDR+OgcWZy11mlpLVuQbZWpcCzKxJW8PVvHo+0rbUJLleCY/GYoRFGgg6HE1vji3lWwHGiUhP87H1cEgQM2/tPXjJVZJuN5cK1UagSU6QaaPH8b9k5gxV7fyRHetL45X9JQULr+qB1X5/LRbE8Ef69VOraZbO+OTRcF57KcQoron3DB0h5jPfQQWKweUcsyt4nQl8cPCVWrSYUaQZQvHjSTfCIntplX9vumrbbYSB5cbRoJDpoUKTQ+elPMUPmFVINJamR5kVpkfSBsHACHNnIeFXX5r5g2tVXJrwJV/CqVsEw0iqQtbhQEYyBW9n0DYA5gd5xf5YFZoawOJmAf2Ou84MV8tryX39kxlYmF9ykgdlh20nrcB1JL/JoJ61u1z/E5yJnscdA4Yhk7ogjvv4tJskI1gI3Px7M8VpZ9eCL0Ag4pUIwNZB0xThE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
