travis:
  secure:
    BINSTAR_TOKEN: PiHq1YUiekSGPrMGhWuQR8fZGJsa3vpoGcKSGT8A1xXP6IbtoHuS6jSrcIC5jbuGT6JofeCOWlc061Cxt/dFVQGGRROCkAoL2noO1M82e0w8d0RLrol2f4gxTalEK8Qh9F6RcsOX+QVIv1DUMozp5Ea9ClhLMgLYIVdfn2l5EQvAtDlfgRcKcBi44+ptPqH/arqVdfPSyY1QS6fXid6KzRPVRFNDCOGElk1lKNEfNOr/xfNlhdUIHucv6gipPrJQRA0qIabAetF5NHN6b9mMy4f24hr0g8Ir/ZUMpJaLPNnxTF/F1bSlQw1Z560kM2OSHN105kHZI6+SDJOSgcIRYCcA2ryKa132Jx2dqoobsqrID25FHMYhiFgW5LaYs7XJig/QMAbxb7o/8ZEV5PKdW1400k+FUTEu4K1sUAreMy03K9ir2HksBfzbk72LW0rM0jOL8QMj1aBShUPR2T7XZZr9zFECSo1vUtlpZ8E7ivUfXaimDBUylNkEsoBauy5uSw59fyOmQMkbXQmubCMef4e3PRM3dnXwEPUYxNzmtvLyCvEgcqe5tPCmaYo2kVL+lzRzpqDo5cz4WrN7ULSdspR6wcxKJJUsmzjmi6zn8GTxcZHwLFae780z4IxOx19lXBXOF12h4h7btwH+KXj2qTJairDo0M9tpFNRqBFgtyQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
