appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: FEgp7fUeVLSkNBuf/W40zla3wLtrYCJ8rf5KnCuo/GznQfMpVlOZbBWwNPqsXTh/YPbgsphPXfpb1sattIVQuKtNe1Xu/Wdd7Mf1chtruSgfME56l9VotoLSMI/PFVNyq0jZKG7WfCEnktsk7uKHRfveRkTf6QJckTS/ylvrMv3ORiokillmUqpAkP9MH8Dmj4XsxkZgDra7C+vVbtZWxqdgxfSr+dmLuNmKRwD6TJz9e5v3edw3IrdHQPMG9+64FAeFO5W6WtRqLUOzW2GEuYuPygK6ru8XCloYTBtic2+dxAwbTX2LSZMkKfnJ2enKb7ViO+cGqiz3V1pztK87mmWEZ4JF+at+icsSP3VGcSsm1jdeVA8miNL9KAnKietcMTdazjEc+y34loxrc5U+cxHD41yQaCrRSlhIFKKls7h3d9VzoxpP5N8ylQZSDUvD1899gqssChKB+zhvL0aMlWKWtGs2K2pgnbi7UyJuSYYHE290uKs0YsP5hysj2JTEw8SjsX+AISV9186PI817j5+auuRvODuFGQitIIpFnT/WR+Di5EiPyoq/y4y2M09puSXsCwkh4eASHEe88VpSKv121zL+4S6KenDfow0qcRY8TtvYHRSXmCsHuqYHVKWvfhfl6F038IMbF5OFLxwmUOzDnvvrN/h5rSJ3/3MVywE=
